default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: app_user_role
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_docker_development

test:
  <<: *default
  database: rails_docker_test

production:
  <<: *default
  database: rails_docker_production
  username: rails_docker
  password: <%= ENV['RAILS_DOCKER_DATABASE_PASSWORD'] %>
